# Generated by Django 5.2.7 on 2026-04-30 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('seating_type', models.CharField(choices=[('reserved', 'Reserved Seating'), ('free', 'Free Seating')], default='free', max_length=20)),
            ],
        ),
    ]
